openapi: 3.0.1
info:
  title: Min
  version: "1.0"
paths:
  /echo:
    post:
      operationId: echoPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - msg
              properties:
                msg:
                  type: string
      responses:
        "200":
          description: OK
